### ISSUE TITLE
Supervised results are similar to unsupervised 

### ISSUE THREAD

**Issue by geneanalyst** [tyjo/dystruct#4]
In a test run with K=6 and 117K SNPs with a genotype rate of 100% using 6 ancient populations represented by 1 to 3 samples per ancient population and 3 modern samples the results were as follows:

Unsupervised- none 0 scores in only 3 columns (not 6 as would be expected for K=6)
Supervised using a text file containing 1 alpha numeric per row to represent samples declared reference and -1 for 3 modern samples to be determined. For example this is is what the abbreviated labels file looked like and invoking —labels

EHG
EHG
ENF
ENF
ENF
WHG
-1
-1

Results were identical with unsupervised

**Comment by tyjo** [comment]
Labels is experimental - I haven't tested this function extensively so use at your own risk. (EDIT: If I can diagnose the problem I am happy to provide a fix for the labeling issue.)

Can you clarify your question? Are your estimates not converging properly? What does your output look like?

**Comment by geneanalyst** [comment]
Thanks. I am attaching the input and output files for your review and comment. parameters are as in your run.sh file with --labels added
[Dystruct_In1.txt](https://github.com/tyjo/dystruct/files/1749456/Dystruct_In1.txt)
[LABELS.txt](https://github.com/tyjo/dystruct/files/1749457/LABELS.txt)



[out_theta.txt](https://github.com/tyjo/dystruct/files/1749460/out_theta.txt)
[temp_theta.txt](https://github.com/tyjo/dystruct/files/1749461/temp_theta.txt)

**Comment by tyjo** [comment]
There were two problems. First, labels were being loaded but not used. Second, your label file should use population numbers for labels, rather than alpha numeric values. I committed a fix for the first problem. Attached is a corrected file for the second.
[LABELS-numbered.txt](https://github.com/tyjo/dystruct/files/1749875/LABELS-numbered.txt)

You may need more individuals to get a signal since these directly affect allele frequency estimates. Roughly, given 6 populations and 21 individuals you only have 3.5 observations per locus.

**Comment by geneanalyst** [comment]
Using the shell script run.sh and changing number of threads to 16 does not shorten process time from threads = 1

**Comment by FIREYWOTAN** [comment]
At times it helps to break down each population. I'm new at working with the components of each group but it has helped me to better understand.

**Comment by tyjo** [comment]
Geneanalyst, benchmarking parallel programs is tricky because a linear increase in the number of threads does not necessarily correspond to a linear increase in runtime.

If each iteration is already fast the overhead for running code in parallel can outweigh the benefits. Additionally, since some sections of the code a parallelized by population, you won't see much of an improvement if the number of threads is greater than the number of populations.
